In [1]:
import numpy as np
from scipy import optimize

### 線形計画法

In [3]:
c = np.array([-3, -4], dtype=np.float64)
G = np.array([[1, 4], [2, 3], [2, 1], [-1, 0], [0, -1]])
h = np.array([1700, 1400, 1000, 0, 0], np.float64)

sol = optimize.linprog(c, A_ub=G, b_ub=h, bounds=(0, None))

print(sol.x)
print(sol.fun)

[400. 200.]
-2000.0


### ２次計画法

In [8]:
!pip install cvxopt

    100% |████████████████████████████████| 5.7MB 3.3MB/s 
You are using pip version 18.0, however version 18.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.


In [9]:
import cvxopt

In [12]:
P = cvxopt.matrix(np.array([[2, 1], [1, 2]], dtype=np.float64))
q = cvxopt.matrix(np.array([2, 4], dtype=np.float64))

sol =cvxopt.solvers.qp(P, q)

print(np.array(sol['x']))
print(np.array(sol['primal objective']))

[[ 1.57009246e-16]
 [-2.00000000e+00]]
-4.0


In [15]:
# 制約付き
P = cvxopt.matrix(np.array([[2, 1], [1, 2]], dtype=np.float64))
q = cvxopt.matrix(np.array([2, 4], dtype=np.float64))
A = cvxopt.matrix(np.array([[1, 1]], dtype=np.float64))
b = cvxopt.matrix(np.array([0], dtype=np.float64))

sol =cvxopt.solvers.qp(P, q, A=A, b=b)

print(np.array(sol['x']))
print(np.array(sol['primal objective']))

[[ 1.]
 [-1.]]
-1.0000000000000013


In [16]:
P = cvxopt.matrix(np.array([[2, 1], [1, 2]], dtype=np.float64))
q = cvxopt.matrix(np.array([2, 4], dtype=np.float64))
G = cvxopt.matrix(np.array([[2, 3]], dtype=np.float64))
h = cvxopt.matrix(np.array([3], dtype=np.float64))

sol =cvxopt.solvers.qp(P, q, G=G, h=h)

print(np.array(sol['x']))
print(np.array(sol['primal objective']))

     pcost       dcost       gap    pres   dres
 0:  1.8858e+00  2.9758e-01  2e+00  0e+00  2e+00
 1: -2.1066e+00 -2.1546e+00  5e-02  2e-16  7e-01
 2: -3.9999e+00 -4.0665e+00  7e-02  6e-16  8e-17
 3: -4.0000e+00 -4.0007e+00  7e-04  9e-16  1e-16
 4: -4.0000e+00 -4.0000e+00  7e-06  3e-16  6e-17
 5: -4.0000e+00 -4.0000e+00  7e-08  3e-16  2e-16
Optimal solution found.
[[-2.45940165e-09]
 [-2.00000001e+00]]
-4.0
