In [1]:
import numpy as np

In [2]:
# 逆行列の計算
a = np.array([[3, 1, 1], [1, 2, 1], [0, -1, 1]])
np.linalg.inv(a)

array([[ 0.42857143, -0.28571429, -0.14285714],
       [-0.14285714,  0.42857143, -0.28571429],
       [-0.14285714,  0.42857143,  0.71428571]])

In [3]:
# 一次方程式を解く
b = np.array([1, 2, 3])
np.linalg.solve(a, b)

array([-0.57142857, -0.14285714,  2.85714286])

In [4]:
from scipy import linalg

In [5]:
# LU分解により連立方程式を解く
a = np.array([[3, 1, 1], [1, 2, 1], [0, -1, 1]])
b = np.array([1, 2, 3])
lu, p = linalg.lu_factor(a)

In [6]:
lu

array([[ 3.        ,  1.        ,  1.        ],
       [ 0.33333333,  1.66666667,  0.66666667],
       [ 0.        , -0.6       ,  1.4       ]])

In [7]:
p

array([0, 1, 2], dtype=int32)

In [8]:
linalg.lu_solve((lu, p), b)

array([-0.57142857, -0.14285714,  2.85714286])