In [1]:
import numpy as np

## 配列の構築

In [2]:
# 整数配列
np.array([1, 4, 2, 5, 3])

array([1, 4, 2, 5, 3])

In [3]:
# 浮動小数へのアップキャスト
# NumPy配列の要素は全て同じ型という制約がある
np.array([3.14, 4, 2, 5, 3])

array([3.14, 4.  , 2.  , 5.  , 3.  ])

In [4]:
# 配列のデータ型を明示的に設定
np.array([1, 4, 2, 5, 3], dtype='float32')

array([1., 4., 2., 5., 3.], dtype=float32)

In [5]:
# 多次元配列
np.array([range(i, i + 3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

### 組み込み関数を利用

In [6]:
# 要素が0の配列
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [7]:
# 要素が１の配列
np.ones((3, 5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [8]:
# 全ての要素が同じ値の配列
np.full((3, 5), 3.14, dtype=float)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [9]:
# シーケンス配列
np.arange(0, 20, 2, dtype=float)

array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18.])

In [20]:
# 指定区間に均等に配置された配列
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [24]:
# 乱数配列の生成
# 0 と 1の間に均一に分布したランダムなあたいの配列を作る
np.random.random((3, 3))

array([[0.45898195, 0.84754747, 0.81075505],
       [0.36891881, 0.17724448, 0.85271074],
       [0.93606541, 0.1634188 , 0.00915094]])

In [29]:
# 正規分布（平均：０、分散：１）
np.random.normal(0, 1, (3, 3))

array([[-0.49257333,  0.80298249,  0.01045489],
       [-1.91512202,  0.53976613, -0.64721985],
       [ 0.42577886, -0.67780169, -0.7905046 ]])

In [33]:
# 区間[0, 10)の間でランダムな整数を生成
np.random.randint(0, 10, (3, 3))

array([[9, 2, 2],
       [1, 0, 1],
       [5, 3, 0]])

In [35]:
# 単位行列
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [37]:
# 初期化されていない配列の生成（初期値はすでにあるメモリの値）
np.empty(10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])