## NumPy配列の属性

In [1]:
import numpy as np
np.random.seed(0) # 乱数シードの設定

x1 = np.random.randint(10, size=6)
x2 = np.random.randint(10, size=(3, 4))
x3 = np.random.randint(10, size=(3, 4, 5))

In [2]:
print(x3.ndim) # 次元数
print(x3.shape) # 各次元のサイズ
print(x3.size) # 合計のサイズ

3
(3, 4, 5)
60


In [3]:
print(x3.dtype) # データ型
print(x3.itemsize) # 各配列要素のサイズ
print(x3.nbytes) # 配列の合計サイズ

int64
8
480


## 配列インデクス：要素へのアクセス

In [4]:
x1

array([5, 0, 3, 3, 7, 9])

In [5]:
x1[0]

5

In [6]:
x1[4]

7

In [7]:
# 配列の後ろから指定する
x1[-1]

9

In [8]:
x1[-2]

7

In [9]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [10]:
x2[0, 0]

3

In [11]:
x2[2, 0]

1

In [12]:
x2[2, -1]

7

In [14]:
# 要素の値の変更 ※データ型は変わらないので注意
x2[0, 0] = 12
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

## 配列のスライス

### １次元配列のスライス

In [15]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
x[:5]

array([0, 1, 2, 3, 4])

In [18]:
x[5:]

array([5, 6, 7, 8, 9])

In [19]:
x[4:7]

array([4, 5, 6])

In [20]:
# 1つおきの要素
x[::2]

array([0, 2, 4, 6, 8])

In [21]:
 x[::3]

array([0, 3, 6, 9])

In [23]:
# インデックス１から始まる２つおきの要素
x[1::2]

array([1, 3, 5, 7, 9])

In [24]:
# 逆順に全ての要素を取得
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [25]:
# インデクス５から逆順に１つおきの要素
x[5::-2]

array([5, 3, 1])

In [26]:
x[5::-1]

array([5, 4, 3, 2, 1, 0])

### 多次元配列のスライス

In [27]:
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [28]:
x2[:2, :3]

array([[12,  5,  2],
       [ 7,  6,  8]])

In [29]:
# 全ての行と１つおきの列
x2[:, ::2]

array([[12,  2],
       [ 7,  8],
       [ 1,  7]])

In [30]:
# 全ての次元を逆順にする
x2[::-1, ::-1]

array([[ 7,  7,  6,  1],
       [ 8,  8,  6,  7],
       [ 4,  2,  5, 12]])

In [32]:
# 最初の列の抽出
x2[:, 0]

array([12,  7,  1])

In [33]:
# 最初の行の抽出
x2[0, :]

array([12,  5,  2,  4])

### ビューとしての部分配列
NumPy配列のスライスは配列のビューを返す。

### 配列のコピー

In [35]:
x2_sub_copy = x2[:2, :2].copy()
print(x2_sub_copy)

[[12  5]
 [ 7  6]]


In [36]:
x2_sub_copy[0, 0] = 42
print(x2_sub_copy)

[[42  5]
 [ 7  6]]


In [37]:
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])