In [ ]:
import numpy as np

### 配列の形状変更

In [4]:
# reshapeメソッド
# 最初の配列の要素数と変更後の要素数が一致している必要がある。
grid = np.arange(1, 10).reshape((3, 3))
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [5]:
x = np.array([1, 2, 3])

In [6]:
# reshapeを使った行ベクトルの作成
x.reshape(1, 3)

array([[1, 2, 3]])

In [7]:
# newaxisを使った行ベクトルの作成
x[np.newaxis, :]

array([[1, 2, 3]])

In [8]:
# reshapeを使った列ベクトルの作成
x.reshape(3, 1)

array([[1],
       [2],
       [3]])

In [9]:
# newaxisを使った列ベクトルの作成
x[:, np.newaxis]

array([[1],
       [2],
       [3]])

### 配列の連結
２つの配列の連結または結合するメソッド
- np.concatenate
- np.vstack
- np.hstack

In [10]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
# 最初の引数としてタプルまたは配列のリストを取る
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [11]:
z = [99, 99, 99]
# ３つ以上の配列の連結も可能
print(np.concatenate([x, y, z]))

[ 1  2  3  3  2  1 99 99 99]


In [12]:
# ２次元配列にも使用可能
grid = np.array([[1, 2, 3],
                       [4, 5, 6]])

In [13]:
# 第１軸（行方向）への連結
np.concatenate([grid, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [14]:
# 第２軸（列方向）への連結
np.concatenate([grid, grid], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [15]:
# np.vstack（垂直スタック）
x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7],
                        [6, 5, 4]])
#　配列を垂直に重ねる
np.vstack([x, grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [16]:
y = np.array([[99],
                     [99]])
np.hstack([grid, y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

### 配列の分割
- np.split
- np.hsplit
- np.vsplit

In [21]:
x = [1, 2, 3, 99, 99, 3, 2, 1]
# 配列と分割点のインデクスのリストを渡すことができる
x1, x2, x3 = np.split(x, [3, 5])
print(x1, x2, x3)

[1 2 3] [99 99] [3 2 1]


N個の分割点を与えるとN+1個に分割されることに注意

In [22]:
grid = np.arange(16).reshape((4, 4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [23]:
upper, lower = np.vsplit(grid, [2])
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [25]:
left, right = np.hsplit(grid, [2])
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


np.dsplitは３番目の軸に沿って配列を分割する