In [2]:
import numpy as np
np.random.seed(0)

## ユニバーサル関数

### ループ処理

In [2]:
def compute_reciprocals(values):
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i] = 1.0 / values[i]
    return output

In [4]:
values = np.random.randint(1, 10, size=5)
%timeit compute_reciprocals(values)

The slowest run took 4.08 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 3: 14.9 µs per loop


In [7]:
big_array = np.random.randint(1, 100, size=1000000)
%timeit compute_reciprocals(values)

The slowest run took 5.26 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 3: 14.8 µs per loop


In [6]:
%timeit (1.0 / big_array)

100 loops, best of 3: 4.36 ms per loop


### NumPy ufunc
単一入力を操作する単項ufuncと２つの入力を操作する二項fuuncの２種類がある

### 配列演算

In [11]:
x = np.arange(4)
print("x        = ", x)
print("x + 5  = ", x + 5)
print("x - 5  = ", x - 5)
print("x * 2  = ", x * 2)
print("x / 2  = ", x / 2)
print("x // 2 = ", x // 2) # 整数除算

x        =  [0 1 2 3]
x + 5  =  [5 6 7 8]
x - 5  =  [-5 -4 -3 -2]
x * 2  =  [0 2 4 6]
x / 2  =  [0.  0.5 1.  1.5]
x // 2 =  [0 0 1 1]


In [12]:
print("-x   = ", -x)
print("x ** 2   = ", x ** 2)
print("x % 2   = ", x % 2)

-x   =  [ 0 -1 -2 -3]
x ** 2   =  [0 1 4 9]
x % 2   =  [0 1 0 1]


#### 絶対値

In [13]:
x = np.array([-2, -1, 0, 1, 2])
abs(x)

array([2, 1, 0, 1, 2])

#### 三角関数

In [3]:
theta = np.linspace(0, np.pi, 3)

In [4]:
print("theta    = ", theta)
print("sin(theta)    = ", np.sin(theta))
print("cos(theta)    = ", np.cos(theta))
print("tan(theta)    = ", np.tan(theta))

theta    =  [0.         1.57079633 3.14159265]
sin(theta)    =  [0.0000000e+00 1.0000000e+00 1.2246468e-16]
cos(theta)    =  [ 1.000000e+00  6.123234e-17 -1.000000e+00]
tan(theta)    =  [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [5]:
x = [-1, 0, 1]
print("x       = ", x)
print("arcsin(x) = ", np.arcsin(x))
print("arccos(x) = ", np.arccos(x))
print("arctan(x) = ", np.arctan(x))

x       =  [-1, 0, 1]
arcsin(x) =  [-1.57079633  0.          1.57079633]
arccos(x) =  [3.14159265 1.57079633 0.        ]
arctan(x) =  [-0.78539816  0.          0.78539816]


#### 指数関数と対数関数

In [6]:
# 指数関数
x = [1, 2, 3]
print("x       = ", x)
print("e^x       = ", np.exp(x))
print("2^x       = ", np.exp2(x))
print("3^x       = ", np.power(3, x))

x       =  [1, 2, 3]
e^x       =  [ 2.71828183  7.3890561  20.08553692]
2^x       =  [2. 4. 8.]
3^x       =  [ 3  9 27]


In [7]:
# 対数関数
x = [1, 2, 4, 10]
print("x       = ", x)
print("ln(x)       = ", np.log(x))
print("log2(x)       = ", np.log2(x))
print("log10(x)       = ", np.log10(x))

x       =  [1, 2, 4, 10]
ln(x)       =  [0.         0.69314718 1.38629436 2.30258509]
log2(x)       =  [0.         1.         2.         3.32192809]
log10(x)       =  [0.         0.30103    0.60205999 1.        ]


In [8]:
# 非常に小さな入力値に対して精度を維持するバージョンもある
x = [0, 0.001, 0.01, 0.1]
print("exp(x) - 1 = ", np.expm1(x))
print("log(1 + x) = ", np.log1p(x))

exp(x) - 1 =  [0.         0.0010005  0.01005017 0.10517092]
log(1 + x) =  [0.         0.0009995  0.00995033 0.09531018]


#### 特殊なufunc：数学関数

In [9]:
from scipy import special

In [10]:
# ガンマ関数
x = [1, 5, 10]
print("gamma(x)    = ", special.gamma(x))
print("ln|gamma(x)    = ", special.gammaln(x))
print("beta(x)    = ", special.beta(x, 2))

gamma(x)    =  [1.0000e+00 2.4000e+01 3.6288e+05]
ln|gamma(x)    =  [ 0.          3.17805383 12.80182748]
beta(x)    =  [0.5        0.03333333 0.00909091]


In [11]:
#  誤差関数（ガウス関数の積分）および相補誤差関数と逆誤差関数
x = np.array([0, 0.3, 0.7, 1.0])
print("erf(x)    = ",special.erf(x))
print("erfc(x)    = ",special.erfc(x))
print("erfinv(x)    = ",special.erfinv(x))

erf(x)    =  [0.         0.32862676 0.67780119 0.84270079]
erfc(x)    =  [1.         0.67137324 0.32219881 0.15729921]
erfinv(x)    =  [0.         0.27246271 0.73286908        inf]


#### ufuncの高度な機能

In [12]:
# 出力の指定をすることで、メモリの節約が可能
x = np.arange(5)
y = np.empty(5)
np.multiply(x, 10, out=y)
print(y)

[ 0. 10. 20. 30. 40.]


In [13]:
y = np.zeros(10)
np.power(2, x, out=y[::2])
print(y)

[ 1.  0.  2.  0.  4.  0.  8.  0. 16.  0.]


In [15]:
# 集約
# reduceは結果が１つになるまで、配列の要素にくり返し演算を適用する
x = np.arange(1, 6)
print(x)
print(np.add.reduce(x))

[1 2 3 4 5]
15


In [16]:
# multiply, reduceで全ての配列の要素の積が得られる
np.multiply.reduce(x)

120

In [17]:
# 中間結果を残す場合はaccumulateを使う
np.multiply.accumulate(x)

array([  1,   2,   6,  24, 120])

In [18]:
# 外積
# ２つの入力の全ての要素の間で計算を行うことができる
x = np.arange(1, 6)
np.multiply.outer(x, x)

array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10],
       [ 3,  6,  9, 12, 15],
       [ 4,  8, 12, 16, 20],
       [ 5, 10, 15, 20, 25]])