In [1]:
import numpy as np

## 集約関数

### 配列を合計する

In [2]:
# 組み込みのsum関数を使う
L = np.random.random(100)
sum(L)

49.01190709076418

In [3]:
# NumPyのsum関数も同じ構文で使用可能
np.sum(L)

49.01190709076419

In [4]:
# NumPyの演算の方が高速
big_array = np.random.random(10000000)
% timeit sum(big_array)
% timeit np.sum(big_array)

1 loop, best of 3: 1.06 s per loop
100 loops, best of 3: 5.48 ms per loop


### 最大と最小

In [5]:
# 組み込みのmin関数、max関数を使用する
min(big_array),max(big_array)

(4.4921259823027526e-08, 0.9999999555474159)

In [6]:
# NumPyの関数の方が高速
np.min(big_array),np.max(big_array)

(4.4921259823027526e-08, 0.9999999555474159)

In [7]:
% timeit min(big_array)
% timeit np.min(big_array)

1 loop, best of 3: 877 ms per loop
100 loops, best of 3: 5.49 ms per loop


In [8]:
# 配列オブジェクト　のメソッドを使用する
print(big_array.min(), big_array.max(), big_array.sum())

4.4921259823027526e-08 0.9999999555474159 5000800.9931322


### 多次元配列の集約
多次元配列の行または列に沿った操作

In [9]:
M = np.random.random((3, 4))
print(M)

[[0.26931741 0.81206005 0.55421042 0.7673038 ]
 [0.38324343 0.34440559 0.00931867 0.49397181]
 [0.62905283 0.01282735 0.23111367 0.51221337]]


In [10]:
# デフォルトは配列全体を集約する
M.sum()

5.019038409709642

In [11]:
# 集約計算する軸を指定するオプションがある
# 例えば、min関数にaxis=0 を指定すると、各列内の最小値を見つけることができる
M.min(axis=0)

array([0.26931741, 0.01282735, 0.00931867, 0.49397181])

In [12]:
# 同様にaxis=1を指定すると各行内の最大値をいつけることができる
M.max(axis=1)

array([0.81206005, 0.49397181, 0.62905283])

In [13]:
# その他の集約関数
np.prod(M) # 要素の積を計算する
np.mean(M) # 要素の平均値を計算する
np.std(M) # 標準偏差を計算する
np.var(M) # 分散を計算する
np.argmin(M) # 最小値のインデクスを返す
np.argmax(M) # 最大値のインデクスを返す
np.median(M) # 要素の中央値を計算する
np.percentile(M, 75) # パーセンタイルを計算する
np.any(M) # いずれかの要素がtrueであるかを評価する
np.all(M) # 全ての要素がtrueであるか評価する

True